# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/avault
    binary: avault
    ldflags:
      -X github.com/JackKrasn/avault/internal/version.GitCommit={{ .Env.GIT_COMMIT }}{{ .Env.GIT_DIRTY }} 
      -X github.com/JackKrasn/avault/internal/version.BuildDate={{ .Env.BUILD_DATE }}
      {{ if .IsSnapshot }} 
      -X github.com/JackKrasn/avault/internal/version.Version={{ .Env.SNAPSHOT_VERSION }}
      {{ else }}
      -X github.com/JackKrasn/avault/internal/version.Version={{ .Env.VERSION }}
      {{ end }}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Env.SNAPSHOT_VERSION }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
